export const LOAD_PLANNED_ACTIVITIES_SUCCESS = "LOAD_PLANNED_ACTIVITIES_SUCCESS";
export const DELETE_PLANNED_ACTIVITY_SUCCESS = "DELETE_PLANNED_ACTIVITY_SUCCESS";
export const UPDATE_PLANNED_ACTIVITY_SUCCESS = "UPDATE_PLANNED_ACTIVITY_SUCCESS";