export const LOAD_PLANNED_ACTIVITIES_SUCCESS = "LOAD_PLANNED_ACTIVITIES_SUCCESS";
export const DELETE_PLANNED_ACTIVITY_SUCCESS = "DELETE_PLANNED_ACTIVITY_SUCCESS";
export const UPDATE_PLANNED_ACTIVITY_SUCCESS = "UPDATE_PLANNED_ACTIVITY_SUCCESS";
export const ADD_PLANNED_ACTIVITY_SUCCESS = "ADD_PLANNED_ACTIVITY_SUCCESS";

export const LOAD_PLANNED_EXERCISES_SUCCESS = "LOAD_PLANNED_EXERCISES_SUCCESS";
export const DELETE_PLANNED_EXERCISE_SUCCESS = "DELETE_PLANNED_EXERCISE_SUCCESS";
export const UPDATE_PLANNED_EXERCISE_SUCCESS = "UPDATE_PLANNED_EXERCISE_SUCCESS";
export const ADD_PLANNED_EXERCISE_SUCCESS = "ADD_PLANNED_EXERCISE_SUCCESS";

export const LOAD_COMPLETED_ACTIVITIES_SUCCESS = "LOAD_COMPLETED_ACTIVITIES_SUCCESS";

export const LOAD_COMPLETED_EXERCISES_SUCCESS = "LOAD_COMPLETED_EXERCISES_SUCCESS";

export const LOAD_ACTIVITY_TYPES_SUCCESS = "LOAD_ACTIVITY_TYPES_SUCCESS";

export const LOAD_EXERCISE_TYPES_SUCCESS = "LOAD_EXERCISE_TYPES_SUCCESS";

export const LOAD_EXERCISE_CATEGORIES_SUCCESS = "LOAD_EXERCISE_CATEGORIES_SUCCESS";

export const LOAD_TRAINING_PLAN_TEMPLATES_SUCCESS = "LOAD_TRAINING_PLAN_TEMPLATES_SUCCESS";
export const COPY_TRAINING_PLAN_TEMPLATE_SUCCESS = "COPY_TRAINING_PLAN_TEMPLATE_SUCCESS";

export const LOAD_USER_INFO_SUCCESS = "LOAD_USER_INFO_SUCCESS"