export const LOAD_PLANNED_ACTIVITIES = "LOAD_PLANNED_ACTIVITIES";
export const LOAD_PLANNED_ACTIVITIES_SUCCESS = "LOAD_PLANNED_ACTIVITIES_SUCCESS";
export const DELETE_PLANNED_ACTIVITY = "DELETE_PLANNED_ACTIVITY";
export const DELETE_PLANNED_ACTIVITY_SUCCESS = "DELETE_PLANNED_ACTIVITY_SUCCESS";
export const UPDATE_PLANNED_ACTIVITY = "UPDATE_PLANNED_ACTIVITY";
export const UPDATE_PLANNED_ACTIVITY_SUCCESS = "UPDATE_PLANNED_ACTIVITY_SUCCESS";
export const ADD_PLANNED_ACTIVITY = "ADD_PLANNED_ACTIVITY";
export const ADD_PLANNED_ACTIVITY_SUCCESS = "ADD_PLANNED_ACTIVITY_SUCCESS";

export const LOAD_PLANNED_RACES = "LOAD_PLANNED_RACES";
export const LOAD_PLANNED_RACES_SUCCESS = "LOAD_PLANNED_RACES_SUCCESS";
export const DELETE_PLANNED_RACE = "DELETE_PLANNED_RACE";
export const DELETE_PLANNED_RACE_SUCCESS = "DELETE_PLANNED_RACE_SUCCESS";
export const UPDATE_PLANNED_RACE = "UPDATE_PLANNED_RACE";
export const UPDATE_PLANNED_RACE_SUCCESS = "UPDATE_PLANNED_RACE_SUCCESS";
export const ADD_PLANNED_RACE = "ADD_PLANNED_RACE";
export const ADD_PLANNED_RACE_SUCCESS = "ADD_PLANNED_RACE_SUCCESS";

export const LOAD_PLANNED_EXERCISES = "LOAD_PLANNED_EXERCISES";
export const LOAD_PLANNED_EXERCISES_SUCCESS = "LOAD_PLANNED_EXERCISES_SUCCESS";
export const DELETE_PLANNED_EXERCISE = "DELETE_PLANNED_EXERCISE";
export const DELETE_PLANNED_EXERCISE_SUCCESS = "DELETE_PLANNED_EXERCISE_SUCCESS";
export const UPDATE_PLANNED_EXERCISE = "UPDATE_PLANNED_EXERCISE";
export const UPDATE_PLANNED_EXERCISE_SUCCESS = "UPDATE_PLANNED_EXERCISE_SUCCESS";
export const ADD_PLANNED_EXERCISE = "ADD_PLANNED_EXERCISE";
export const ADD_PLANNED_EXERCISE_SUCCESS = "ADD_PLANNED_EXERCISE_SUCCESS";

export const LOAD_COMPLETED_ACTIVITIES = "LOAD_COMPLETED_ACTIVITIES";
export const LOAD_COMPLETED_ACTIVITIES_SUCCESS = "LOAD_COMPLETED_ACTIVITIES_SUCCESS";
export const ADD_COMPLETED_ACTIVITIES = "ADD_COMPLETED_ACTIVITIES";
export const ADD_COMPLETED_ACTIVITIES_SUCCESS = "ADD_COMPLETED_ACTIVITIES_SUCCESS";

export const LOAD_COMBINED_RECENT_ACTIVITIES = "LOAD_COMBINED_RECENT_ACTIVITIES";
export const LOAD_COMBINED_RECENT_ACTIVITIES_SUCCESS = "LOAD_COMBINED_RECENT_ACTIVITIES_SUCCESS";

export const LOAD_COMPLETED_EXERCISES_SUCCESS = "LOAD_COMPLETED_EXERCISES_SUCCESS";
export const ADD_COMPLETED_EXERCISE = "ADD_COMPLETED_EXERCISE";
export const ADD_COMPLETED_EXERCISE_SUCCESS = "ADD_COMPLETED_EXERCISE_SUCCESS";
export const UPDATE_COMPLETED_EXERCISE = "UPDATE_COMPLETED_EXERCISE";
export const UPDATE_COMPLETED_EXERCISE_SUCCESS = "UPDATE_COMPLETED_EXERCISE_SUCCESS";

export const LOAD_ACTIVITY_TYPES = "LOAD_ACTIVITY_TYPES";
export const LOAD_ACTIVITY_TYPES_SUCCESS = "LOAD_ACTIVITY_TYPES_SUCCESS";

export const LOAD_EXERCISE_TYPES_SUCCESS = "LOAD_EXERCISE_TYPES_SUCCESS";

export const LOAD_EXERCISE_CATEGORIES_SUCCESS = "LOAD_EXERCISE_CATEGORIES_SUCCESS";

export const LOAD_TRAINING_PLAN_TEMPLATES_SUCCESS = "LOAD_TRAINING_PLAN_TEMPLATES_SUCCESS";
export const COPY_TRAINING_PLAN_TEMPLATE_SUCCESS = "COPY_TRAINING_PLAN_TEMPLATE_SUCCESS";

export const LOAD_USER_INFO = "LOAD_USER_INFO";
export const LOAD_USER_INFO_SUCCESS = "LOAD_USER_INFO_SUCCESS";
export const UPDATE_USER_INFO = "UPDATE_USER_INFO";
export const UPDATE_USER_INFO_SUCCESS = "UPDATE_USER_INFO_SUCCESS";
export const STORE_USER_STRAVA_ACCESS_TOKEN = "STORE_USER_STRAVA_ACCESS_TOKEN";

export const LOAD_ANNUAL_STATS = "LOAD_ANNUAL_STATS";
export const LOAD_ANNUAL_STATS_SUCCESS = "LOAD_ANNUAL_STATS_SUCCESS";

export const SHOW_ALERT = "SHOW_ALERT";

export const ERROR_ENCOUNTERED = "ERROR_ENCOUNTERED";